
SELECT * 
WHERE 
{ ?language  <http://www.wikidata.org/prop/direct/P31>  ?instance ;
            <http://www.wikidata.org/prop/direct/P17>  <http://www.wikidata.org/entity/Q55>
  
  OPTIONAL
    { ?wikipedia  <http://www.wikidata.org/prop/direct/P31>  <http://www.wikidata.org/entity/Q10876391> ;
                <http://www.wikidata.org/prop/direct/P407>  ?language
    }

}
