
SELECT * 
WHERE 
{ ?item   <http://www.wikidata.org/prop/direct/P39>  <http://www.wikidata.org/entity/Q3044918> ;
          <http://www.wikidata.org/prop/direct/P19>  ?place .
  ?place  <http://www.wikidata.org/prop/direct/P17>  ?country
  

}
