
SELECT * 
WHERE 
{ ?standard  <http://www.wikidata.org/prop/direct/P1462>  <http://www.wikidata.org/entity/Q37033>
  OPTIONAL
    { ?standard  <http://www.wikidata.org/prop/direct/P856>  ?website }

}
