
SELECT * 
WHERE 
{ ?object  <http://www.wikidata.org/prop/direct/P31>  <http://www.wikidata.org/entity/Q13442814> ;
           <http://www.wikidata.org/prop/direct/P50>  ?author .
  ?author  <http://www.wikidata.org/prop/direct/P106>  ?occupation

}
