
SELECT * 
WHERE 
{ ?item  <http://www.wikidata.org/prop/direct/P180>  <http://www.wikidata.org/entity/Q243> ;
         <http://www.wikidata.org/prop/direct/P31>  ?instance
  OPTIONAL
    { ?item  <http://www.wikidata.org/prop/direct/P170>  ?creator }
  OPTIONAL
    { ?item  <http://www.wikidata.org/prop/direct/P571>  ?date }
  OPTIONAL
    { ?item  <http://www.wikidata.org/prop/direct/P18>  ?image }

}
