
SELECT * 
WHERE 
{ <http://dbpedia.org/resource/Les_Mis%C3%A9rables>
            <http://xmlns.com/foaf/0.1/name>  ?title ;
            <http://www.w3.org/2000/01/rdf-schema#comment>  ?description
  
  OPTIONAL
    {   { ?sameas  <http://www.w3.org/2002/07/owl#sameAs>  <http://dbpedia.org/resource/Les_Mis%C3%A9rables> }
      UNION
        { <http://dbpedia.org/resource/Les_Mis%C3%A9rables>
                    <http://www.w3.org/2002/07/owl#sameAs>  ?sameas
        }
    }
}
