
SELECT * 
WHERE 
{ OPTIONAL
    { <http://dbpedia.org/resource/шлюха>
                <http://dbpedia.org/property/abstract>  ?abstract
    }
  OPTIONAL
    { <http://dbpedia.org/resource/шлюха>
                <http://dbpedia.org/abstract>  ?abstract
    }

}
