
SELECT * 
WHERE 
{ <http://dbpedia.org/ontology/startPoint>
            a                     <http://www.w3.org/2002/07/owl#ObjectProperty> .
  ?val      <http://dbpedia.org/ontology/startPoint>  ?b
}
