
SELECT * 
WHERE 
{ ?person  <http://dbpedia.org/property/birthPlace>  <http://dbpedia.org/resource/Berlin> ;
           <http://dbpedia.org/ontology/birthDate>  ?birth ;
           <http://xmlns.com/foaf/0.1/name>  ?name ;
           <http://dbpedia.org/ontology/deathDate>  ?death

}
