
SELECT * 
WHERE 
{ {   { <http://dbpedia.org/resource/Hershey_Foods>
                  <http://dbpedia.org/property/redirect>  ?company
      }
    UNION
      { <http://dbpedia.org/resource/The_Hershey_Company>
                  <http://dbpedia.org/property/redirect>  ?company
      }
    UNION
      { ?company  <http://dbpedia.org/property/homepage>  <http://www.hersheys.com> }
    UNION
      { ?company  <http://dbpedia.org/property/homepage>  <http://www.hersheys.com/> }
    UNION
      { ?company  <http://dbpedia.org/property/symbol>  "HSY" }
    UNION
      { ?company  <http://www.w3.org/2000/01/rdf-schema#label>  "The Hershey Company"@en }
    UNION
      { ?company  <http://www.w3.org/2000/01/rdf-schema#label>  "Hershey Foods"@en }
    UNION
      { ?company  <http://www.w3.org/2000/01/rdf-schema#label>  "Hershey Foods"@en }
    UNION
      { ?company  <http://dbpedia.org/property/name>  "The Hershey Company"@en }
    UNION
      { ?company  <http://dbpedia.org/property/companyName>  "The Hershey Company"@en }
    UNION
      { ?company  <http://xmlns.com/foaf/0.1/name>  "The Hershey Company" }
  }
  { ?company  a                     ?type
  
  }
  { ?company  <http://www.w3.org/2000/01/rdf-schema#label>  ?label
  
  }
  OPTIONAL
    {   { ?company  <http://dbpedia.org/property/homepage>  ?webaddress }
      UNION
        { ?company  <http://dbpedia.org/property/companyName>  ?companyName }
      UNION
        { ?company  <http://dbpedia.org/property/symbol>  ?symbol }
      UNION
        { ?company  <http://www.w3.org/2002/07/owl#sameAs>  ?sameAsUri }
      UNION
        { ?company  <http://xmlns.com/foaf/0.1/page>  ?linkUrl }
    }
}
