
SELECT * 
WHERE 
{ {   { ?place  <http://www.w3.org/2000/01/rdf-schema#label>  "Cebu"@en }
    UNION
      { ?place  <http://www.w3.org/2000/01/rdf-schema#label>  "Cebu, Philippines"@en }
    UNION
      { ?place  <http://dbpedia.org/property/officialName>  "Cebu"@en }
    UNION
      { ?place  <http://dbpedia.org/property/name>  "Cebu"@en }
    UNION
      { ?place  <http://xmlns.com/foaf/0.1/name>  "Cebu"@en }
    UNION
      { ?place  <http://www.w3.org/2002/07/owl#sameAs>  <http://rdf.freebase.com/ns/guid.9202a8c04000641f8000000000129603> }
  }
  {   { ?place  a                     ?type
      
      }
    UNION
      { ?place  <http://dbpedia.org/property/wikiPageUsesTemplate>  <http://dbpedia.org/resource/Template:coord> }
  }
  { ?place  <http://www.w3.org/2000/01/rdf-schema#label>  ?label
  
  }
  OPTIONAL
    {   { ?place  <http://www.w3.org/2003/01/geo/wgs84_pos#lat>  ?latitude ;
                  <http://www.w3.org/2003/01/geo/wgs84_pos#long>  ?longitude
        }
      UNION
        { ?place  <http://www.w3.org/2002/07/owl#sameAs>  ?sameAsUri }
      UNION
        { ?place  <http://xmlns.com/foaf/0.1/page>  ?linkUrl }
    }
}
