
SELECT * 
WHERE 
{ ?actor2  a                     <http://dbpedia.org/ontology/Actor> ;
           <http://xmlns.com/foaf/0.1/name>  ?actor_name_en ;
           <http://dbpedia.org/ontology/birthDate>  ?birth_date

}
