
SELECT * 
WHERE 
{ <http://dbpedia.org/resource/Between_the_Hills>
            ?property  ?hasValue
  OPTIONAL
    { ?hasValue  <http://www.w3.org/2000/01/rdf-schema#label>  ?itemlabel }
  OPTIONAL
    { ?property  <http://www.w3.org/2000/01/rdf-schema#label>  ?label }

}
